# Generated by Django 5.2.5 on 2025-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscribe_to_newsletter",
            field=models.BooleanField(default=False),
        ),
    ]
